import type {
  ApiMenuCategory,
  ApiMenuItem,
  ApiRestaurant,
} from "@/types/api";

const img = (seed: string) => `https://picsum.photos/seed/${seed}/640/420`;

export const MOCK_RESTAURANTS: ApiRestaurant[] = [
  {
    id: 1,
    slug: "dastarkhan-almaty",
    name: "Дастархан",
    description: "Традиционная казахская кухня: бешбармак, куырдак, баурсаки.",
    cuisine_types: ["Казахская"],
    city: "Алматы",
    address: "ул. Достык, 91",
    rating: 4.8,
    rating_count: 612,
    price_level: 2,
    delivery_time_min: 30,
    delivery_time_max: 45,
    delivery_fee: 500,
    min_order_amount: 3000,
    image_url: img("dastarkhan"),
    is_open: true,
    tags: ["Популярно", "Нац. кухня"],
  },
  {
    id: 2,
    slug: "sushiya",
    name: "Sushiya",
    description: "Свежие суши и роллы, доставка в термосумках.",
    cuisine_types: ["Японская", "Суши"],
    city: "Алматы",
    address: "пр. Абая, 44",
    rating: 4.6,
    rating_count: 389,
    price_level: 2,
    delivery_time_min: 35,
    delivery_time_max: 55,
    delivery_fee: 700,
    min_order_amount: 4000,
    image_url: img("sushiya"),
    is_open: true,
    tags: ["Суши", "Новинка"],
  },
  {
    id: 3,
    slug: "napoli-pizza",
    name: "Napoli Pizza",
    description: "Пицца на тонком тесте в дровяной печи.",
    cuisine_types: ["Итальянская", "Пицца"],
    city: "Алматы",
    address: "ул. Жибек Жолы, 135",
    rating: 4.7,
    rating_count: 501,
    price_level: 2,
    delivery_time_min: 25,
    delivery_time_max: 40,
    delivery_fee: 600,
    min_order_amount: 3500,
    image_url: img("napoli"),
    is_open: true,
    tags: ["Пицца", "Быстро"],
  },
  {
    id: 4,
    slug: "burger-brothers",
    name: "Burger Brothers",
    description: "Сочные бургеры из мраморной говядины и картофель фри.",
    cuisine_types: ["Американская", "Бургеры"],
    city: "Алматы",
    address: "ул. Толе би, 60",
    rating: 4.5,
    rating_count: 743,
    price_level: 1,
    delivery_time_min: 20,
    delivery_time_max: 35,
    delivery_fee: 400,
    min_order_amount: 2500,
    image_url: img("burger"),
    is_open: true,
    tags: ["Бургеры", "Хит"],
  },
  {
    id: 5,
    slug: "tbilisi-house",
    name: "Tbilisi House",
    description: "Хачапури, хинкали и грузинские вина.",
    cuisine_types: ["Грузинская"],
    city: "Алматы",
    address: "ул. Кабанбай батыра, 78",
    rating: 4.9,
    rating_count: 288,
    price_level: 3,
    delivery_time_min: 40,
    delivery_time_max: 60,
    delivery_fee: 800,
    min_order_amount: 5000,
    image_url: img("tbilisi"),
    is_open: true,
    tags: ["Премиум"],
  },
  {
    id: 6,
    slug: "green-bowl",
    name: "Green Bowl",
    description: "Полезные боулы, салаты и веганское меню.",
    cuisine_types: ["Вегетарианская", "Здоровое питание"],
    city: "Алматы",
    address: "ул. Сатпаева, 30",
    rating: 4.4,
    rating_count: 156,
    price_level: 2,
    delivery_time_min: 25,
    delivery_time_max: 40,
    delivery_fee: 500,
    min_order_amount: 3000,
    image_url: img("greenbowl"),
    is_open: false,
    tags: ["Веган", "ЗОЖ"],
  },
  {
    id: 7,
    slug: "coffee-lab",
    name: "Coffee Lab",
    description: "Спешелти кофе, десерты и завтраки весь день.",
    cuisine_types: ["Кофе и десерты"],
    city: "Алматы",
    address: "ул. Гоголя, 86",
    rating: 4.6,
    rating_count: 402,
    price_level: 1,
    delivery_time_min: 15,
    delivery_time_max: 30,
    delivery_fee: 350,
    min_order_amount: 2000,
    image_url: img("coffeelab"),
    is_open: true,
    tags: ["Завтраки", "Кофе"],
  },
  {
    id: 8,
    slug: "wok-street",
    name: "Wok Street",
    description: "Азиатская кухня вок: лапша, рис, димсамы.",
    cuisine_types: ["Азиатская", "Китайская"],
    city: "Алматы",
    address: "ул. Розыбакиева, 247",
    rating: 4.3,
    rating_count: 219,
    price_level: 1,
    delivery_time_min: 20,
    delivery_time_max: 35,
    delivery_fee: 450,
    min_order_amount: 2500,
    image_url: img("wokstreet"),
    is_open: true,
    tags: ["Азия", "Быстро"],
  },
];

const categoryNames = ["Стартеры", "Основные блюда", "Напитки", "Десерты"];

function buildCategories(restaurantId: number): ApiMenuCategory[] {
  return categoryNames.map((name, i) => ({
    id: restaurantId * 10 + i + 1,
    restaurant_id: restaurantId,
    name,
    sort_order: i,
  }));
}

const MENU_BY_RESTAURANT: Record<number, { name: string; description: string; price: number; categoryOffset: number; tags?: string[] }[]> = {
  1: [
    { name: "Бешбармак с кониной", description: "Традиционное блюдо с домашней лапшой", price: 3800, categoryOffset: 1 },
    { name: "Куырдак", description: "Жареные субпродукты с луком и картофелем", price: 3200, categoryOffset: 1 },
    { name: "Баурсаки", description: "Порция домашних баурсаков", price: 1200, categoryOffset: 0 },
    { name: "Шубат", description: "Кисломолочный напиток из верблюжьего молока", price: 900, categoryOffset: 2 },
    { name: "Шек-шек", description: "Сладкое лакомство из теста и мёда", price: 1500, categoryOffset: 3 },
  ],
  2: [
    { name: "Филадельфия ролл", description: "Лосось, сливочный сыр, огурец", price: 3200, categoryOffset: 1, tags: ["Хит"] },
    { name: "Калифорния ролл", description: "Краб, авокадо, икра тобико", price: 2900, categoryOffset: 1 },
    { name: "Мисо суп", description: "Классический японский суп", price: 1200, categoryOffset: 0 },
    { name: "Сашими сет", description: "Ассорти из свежей рыбы", price: 4500, categoryOffset: 1 },
    { name: "Зелёный чай", description: "Горячий японский чай", price: 700, categoryOffset: 2 },
  ],
  3: [
    { name: "Маргарита", description: "Томаты, моцарелла, базилик", price: 3400, categoryOffset: 1 },
    { name: "Пепперони", description: "Острая колбаса пепперони, сыр", price: 3900, categoryOffset: 1, tags: ["Острое"] },
    { name: "Кватро формаджи", description: "Четыре вида сыра", price: 4200, categoryOffset: 1 },
    { name: "Брускетта", description: "Хрустящий хлеб с томатами и базиликом", price: 1800, categoryOffset: 0 },
    { name: "Тирамису", description: "Классический итальянский десерт", price: 2100, categoryOffset: 3 },
  ],
  4: [
    { name: "Классический бургер", description: "Говяжья котлета, чеддер, соус фирменный", price: 2400, categoryOffset: 1 },
    { name: "Бекон бургер", description: "Двойное мясо, бекон, барбекю соус", price: 2900, categoryOffset: 1, tags: ["Хит"] },
    { name: "Картофель фри", description: "Хрустящий картофель фри", price: 1100, categoryOffset: 0 },
    { name: "Милкшейк", description: "Ванильный молочный коктейль", price: 1500, categoryOffset: 2 },
  ],
  5: [
    { name: "Хачапури по-аджарски", description: "Лодочка с сыром и яйцом", price: 3100, categoryOffset: 1 },
    { name: "Хинкали", description: "5 штук, мясная начинка", price: 2800, categoryOffset: 1 },
    { name: "Лобио", description: "Тушёная фасоль по-грузински", price: 2200, categoryOffset: 0 },
    { name: "Чурчхела", description: "Домашняя чурчхела", price: 1300, categoryOffset: 3 },
  ],
  6: [
    { name: "Боул Будда", description: "Киноа, авокадо, овощи гриль", price: 3200, categoryOffset: 1 },
    { name: "Салат Цезарь веган", description: "С тофу вместо курицы", price: 2600, categoryOffset: 0 },
    { name: "Смузи манго-банан", description: "Свежевыжатый смузи", price: 1600, categoryOffset: 2 },
  ],
  7: [
    { name: "Капучино", description: "Классический капучино", price: 1200, categoryOffset: 2 },
    { name: "Круассан с миндалём", description: "Свежая выпечка", price: 1400, categoryOffset: 3 },
    { name: "Авокадо тост", description: "На цельнозерновом хлебе", price: 2200, categoryOffset: 0 },
    { name: "Чизкейк Нью-Йорк", description: "Классический чизкейк", price: 1900, categoryOffset: 3 },
  ],
  8: [
    { name: "Вок с курицей", description: "Лапша удон, овощи, соус терияки", price: 2600, categoryOffset: 1 },
    { name: "Димсамы", description: "6 штук на пару", price: 2100, categoryOffset: 0 },
    { name: "Острый вок с говядиной", description: "Рис, овощи, острый соус", price: 2900, categoryOffset: 1, tags: ["Острое"] },
  ],
};

export function getMockCategories(restaurantId: number): ApiMenuCategory[] {
  return buildCategories(restaurantId);
}

export function getMockMenuItems(restaurantId: number): ApiMenuItem[] {
  const categories = buildCategories(restaurantId);
  const items = MENU_BY_RESTAURANT[restaurantId] ?? [];
  return items.map((item, i) => ({
    id: restaurantId * 100 + i + 1,
    restaurant_id: restaurantId,
    category_id: categories[item.categoryOffset].id,
    name: item.name,
    description: item.description,
    price: item.price,
    image_url: img(`${restaurantId}-item-${i}`),
    is_available: true,
    tags: item.tags ?? [],
  }));
}
